#!/usr/bin/env python3
# Octavia does not generate a wsgi_scripts entry point via pbr/setuptools;
# this file is carried from the RDO octavia-distgit repo (Source17:
# octavia-wsgi) since it is not shipped in the upstream source tree.

import threading

from octavia.api.app import setup_app


application = None
app_lock = threading.Lock()

with app_lock:
    if application is None:
        application = setup_app()
